PPRC-4: founding members can never be revoked.
tmackenzie/ping-pong-champion-rules pull request #18
Opened 2018-11-28 23:16 UTC by tmackenzie

2018-11-28 23:19 UTC, fawaad reviewed
I think he prefers Joshua. And I'm not considered a founding member?

2018-11-29 01:44 UTC, tmackenzie commented
@fawaad hmmm,  were you a founder?

2018-11-30 19:49 UTC, jeffborders requested changes
👎

2018-11-30 19:49 UTC, jeffborders commented
💩

2019-03-18 21:48 UTC, merged